apiVersion: apps/v1
kind: Deployment
metadata:
  name: kedify-sample-minute-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kedify-sample-minute-metrics
  template:
    metadata:
      labels:
        app: kedify-sample-minute-metrics
    spec:
      containers:
      - name: kedify-sample-minute-metrics
        image: ghcr.io/kedify/sample-minute-metrics:latest
        ports:
        - containerPort: 8080
        env:
        - name: SCHEDULE
          value: "0:8,1:0,2:4,3:2,4:0,5:3,7:5,9:0"
---
apiVersion: v1
kind: Service
metadata:
  name: kedify-sample-minute-metrics
spec:
  selector:
    app: kedify-sample-minute-metrics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
