apiVersion: batch/v1
kind: Job
metadata:
  generateName: sqs-producer-
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: aws-sqs
      containers:
        - name: sqs-producer
          image: amazon/aws-cli:2.15.23
          env:
            - name: QUEUE_URL
              value: "<put-your-sqs-queue-url-here>" # Replace with your SQS queue URL
            - name: NUM_MESSAGES
              value: "10" # Replace with the number of messages you want to send
          command: ["/bin/bash", "-c"]
          args:
            - |
              for i in $(seq 1 $NUM_MESSAGES); do
                aws sqs send-message --queue-url "$QUEUE_URL" --message-body "Hello from message $i";
                echo "Message $i sent";
              done
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Never
  backoffLimit: 4
