apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stable-diffusion-webui
  name: stable-diffusion-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion-webui
  template:
    metadata:
      labels:
        app: stable-diffusion-webui
    spec:
      containers:
      # - image: ghcr.io/kedify/stable-diffusion-webui
      - image: jkremser/stable-diffusion-webui
        name: stable-diffusion-webui
        volumeMounts:
        - name: shared-images
          mountPath: /app/public/generated
      - image: minio/mc
        name: minio-sidecar
        env:
        - name: MINIO_USERNAME
          valueFrom:
            secretKeyRef:
              name: minio
              key: rootUser
        - name: MINIO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio
              key: rootPassword
        - name: AMQP_URL
          valueFrom:
            secretKeyRef:
              name: stablediff-rabbitmq
              key: host

        command: ["/bin/sh", "-c"]
        args:
        - |
          mc alias set shared http://minio:9000 $MINIO_USERNAME $MINIO_PASSWORD;
          mc admin info shared;
          echo "Minio configured, starting sync.."
          mc mirror --watch --exclude *.json shared/images /images;

        volumeMounts:
        - name: shared-images
          mountPath: /images
      volumes:
      - name: shared-images
        emptyDir: {}
