apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: rabbitmq-scaledjob
  namespace: default
spec:
  jobTargetRef:
    template:
      spec:
        containers:
          - name: consumer-program
            image: sharadregoti/consumer-program:v0.1.0
            env:
              - name: COUNTER_COUNT_URL
                value: "http://counter-service:8080/create/count"
              - name: COUNTER_KILL_URL
                value: "http://counter-service:8080/kill/count"
              - name: SLEEP_TIME
                value: "600"
              - name: RABBITMQ_URL
                valueFrom:
                  secretKeyRef:
                    name: rabbitmq-credentials
                    key: address
              # Define your container specs here
        restartPolicy: Never
  pollingInterval: 10 # How often KEDA will check the RabbitMQ queue
  successfulJobsHistoryLimit: 100 # Number of successful jobs to keep
  failedJobsHistoryLimit: 100 # Number of failed jobs to keep
  maxReplicaCount: 100 # Maximum number of jobs that KEDA can create
  scalingStrategy:
    strategy: "default" # Scaling strategy (default, custom, or accurate)
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: testqueue
        mode: QueueLength
        value: "1" # Number of messages per job
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn
