apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: fastsdcpu
    contents:
      - path: .
        git:
          url: https://github.com/rupeshs/fastsdcpu
          ref: origin/main
          newRootPath: fastsdcpu
