name: Build and push images for stable diffusion use-case
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  workflow_call:
    inputs:
      imageTag:
        description: "container image tag"
        required: false
        default: latest
        type: string

env:
  CONTAINER_IMG_REGISTRY: ghcr.io
  CONTAINER_IMG_ORG: kedify
  CONTAINER_IMG_WORKER_NAME: stable-diffusion-worker
  CONTAINER_IMG_WEBUI_NAME: stable-diffusion-webui
  CONTAINER_IMG_TAG: ${{ inputs.imageTag || 'latest' }}

jobs:
  build-container:
    permissions:
      contents: write # for creation of releases
      packages: write # push images
      id-token: write # needed for signing the images with GitHub OIDC Token
    name: build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
      
      - name: Install Syft
        uses: anchore/sbom-action@v0

      - name: Build and push
        env:
          WORKER_IMAGE: "${{ env.CONTAINER_IMG_REGISTRY }}/${{ env.CONTAINER_IMG_ORG }}/${{ env.CONTAINER_IMG_WORKER_NAME }}:${{ env.CONTAINER_IMG_TAG }}"
          WEBUI_IMAGE: "${{ env.CONTAINER_IMG_REGISTRY }}/${{ env.CONTAINER_IMG_ORG }}/${{ env.CONTAINER_IMG_WEBUI_NAME }}:${{ env.CONTAINER_IMG_TAG }}"
        run: |
          cd samples/stable-diffusion/
          make build-multiarch-images
